#!/bin/bash

set -e
set -u
set -x

TARGET=${TARGET:-..}
cd $TARGET

export OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
/opt/omero/server/venv3/bin/python3 setup.py test -t test -i ${OMERO_DIST}/etc/ice.config -v
