#!/bin/bash

set -e
set -u
set -x

TARGET=${TARGET:-..}
cd $TARGET

export OMERO_DIST=${OMERO_DIST:-/opt/omero/server/OMERO.server}
export PYTHONPATH=${OMERO_DIST}/lib/python
python setup.py test -t test -i ${OMERO_DIST}/etc/ice.config -v
